---
services:
  matter-server:
    container_name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    network_mode: host
    security_opt:
      - apparmor:unconfined
    volumes:
      - /run/dbus:/run/dbus:ro
      - ../store/matter:/data
    restart: unless-stopped