---
services:
  mosquitto:
    user: "${UID}:${GID}"
    container_name: mosquitto
    image: eclipse-mosquitto
    network_mode: host
    volumes:
      - ${STACKS_CONFIG}/mosquitto:/mosquitto/config
      - ${STACKS_VOLUME}/mosquitto/data:/mosquitto/data
      - ${STACKS_VOLUME}/mosquitto/log:/mosquitto/log
    restart: unless-stopped